apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user
subjects:
- kind: ServiceAccount
  name: alochym
  namespace: default
