apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: useraccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alochym
