apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: user-permission
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - list
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - list
  - delete
  - watch
