apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: user-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-permission
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alochym
