# Create a Pod called redis-storage with image: redis:alpine with a Volume of type emptyDir that lasts for the life of the Pod. Use volumeMount with mountPath = /data/redis.
# kubectl -n practice exec -it -- ls /data/redis
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis-storage
  name: redis-storage
  namespace: practice
spec:
  volumes:
    - name: empty-dir
      emptyDir: {}
  containers:
  - image: redis:alpine
    name: redis-storage
    volumeMounts:
      - name: empty-dir
        mountPath: /data/redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
