# Create a PersistentVolumeClaim called 'mypvc-practice' requesting 400Mi with accessMode of 'ReadWriteOnce' and storageClassName of normal.
# Check the status of the PersistenVolume.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-practice
  namespace: practice
spec:
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi 
