# Create a configMap called 'mysecret' with value password=pas. Create a new nginx-opt pod that loads the value from key 'password' in an env variable called 'PASSWORD'.
# kubectl run nginx --image=nginx:1.18-alpine --dry-run=client -oyaml -n practice
# kubecrtl exec -it -n practice nginx -- env
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-secret
  namespace: practice
spec:
  containers:
  - image: nginx:1.18-alpine
    name: nginx
    resources: {}
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

