# Create a configmap 'my-config' with values 'key1=val1' and 'key2=val2'. Load this configmap as a volume into a nginx-sec pod.
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-secret-2
  namespace: practice
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret
  containers:
  - image: nginx:1.18-alpine
    name: nginx
    resources: {}
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/spartaa
    envFrom:
      - secretRef:
          name: mysecret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
