# Create a service called messaging-service to expose the messaging application within the cluster on port 6379 and describe it.
# kubectl run messaging-service --image=redis:alpine -l tier=msg --port=6379 --expose --dry-run=client -oyaml |tee 07-pod-service.yaml
# kubectl expose --name=messaging-service pod messaging-service -n practice --port=6379
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    tier: msg
  name: messaging-service
  namespace: practice
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    tier: msg
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: msg
  name: messaging-service
  namespace: practice
spec:
  containers:
  - image: redis:alpine
    name: messaging-service
    ports:
    - containerPort: 6379
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
