apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: production
    app: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                # operator values [In, NotIn, Exists, DoesNotExist]
                operator: In # node anti affinity => operator: NotIn
                values:
                  - ssd
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
