apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: alochym
  labels:
    environment: production
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
