apiVersion: v1
kind: Pod
metadata:
  name: nginx-ok
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx:1.18.0-alpine
  tolerations:
    - key: "alochym"
      operator: "Exists"
      effect: "NoSchedule"
