apiVersion: v1
kind: Pod
metadata:
  name: pod-with-http-readiness
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      # defines the health checking
      readinessProbe:
        # an http probe
        httpGet:
          path: /_status/healthz
          port: 80
        initialDelaySeconds: 30
        timeoutSeconds: 1
      ports:
        - containerPort: 80
